const types =  Object.freeze({
    SET_MODES: "SET_MODES",
    SET_ACTIVE_MODE: "SET_ACTIVE_MODE",
    START_ACTIVE_MODE: "START_ACTIVE_MODE",
    SET_HOVER_SQUARE: "SET_HOVER_SQUARE",
    REMOVE_HOVER_SQUARE: "REMOVE_HOVER_SQUARE",
    REMOVE_SQUARES: "REMOVE_SQUARES"
});

export default types;